author: Precipicegames
database: false
description: Plugin to automatically level items based on activity
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: com.precipicegames.autoenchanter.Autoenchanter
name: AutoEnchanter
startup: postworld
url: http://precipicegames.com/
version: '1.1'
